### ISSUE TITLE
Cannot find MainActivity

### ISSUE THREAD

**Issue by ElenaNH** [ElenaNH/NMedia_Error#2]
Попыталась применить модель mvvm, как в лекции, но не сработало.

Проект собирается, пишет в Event Log, что все прекрасно, __запускается и немедленно падает__.
В Logcat в первый раз я увидела сообщение, что не найден MainActivity (хотя он есть)

Теперь же у меня в Logcat в принципе пусто - нет сообщений - после того, как я согласилась установить какие-то связанные с ним дополнения фильтрации (думала - раз предлагает android studio, то надо соглашаться, а вышло только хуже)

При этом в макете activity_main тоже красным цветом отмечается MainActivity (строка tools:context=".MainActivity")

Кроме того, полностью как в материалах к лекции сделать файлы build.gradle у меня тоже не получилось - падала сборка, когда я копировала из скачанных файлов примеров. 
В результате по одному шажочку я пришла к собственному результату, который (как мне ___кажется___) должен быть идентичен по всем версиям тому, что в доп. материалах нам дано, но что-то все же не так, раз одно собирается, а другое нет.

Прошу помощи, спасибо.

**Comment by vOrzee** [comment]
У Вас в MainActivity прописан
 **package ru.netology.nmedia.activity**
Однако само MainActivity находится в корневом каталоге, можно либо создать package activity и поместить его туда, либо заменить на:
**package ru.netology.nmedia**.
в xml файле в tools:context должно совпадать с относительным путём package (либо .activity.MainActivity, либо .MainActivity, в зависимости от реализации)

**Comment by ElenaNH** [comment]
Разобралась
